# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09c851e9ab5ef82f8493c32144be3e41f593095ee37cdc099507348603078c6cec75f4dde28a133356ed5eac41e46e8164d76cbcf556ef9aed5804e855726043

test:
  secret_key_base: fdffd351a9ebd316b775654655c74e3649d24d8fbf6ff7d4aa0436886c854937e8dbe7d80e24688fdc258159f0d8c52966784c1422a92e11ff8d05f625db2d19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
